Repository S-CON-SKHU/S_CON_WEB, pull requests merged in 2022-04, with the labels that each got.

#14 [#10] apply List page, add data list
  src/assets/images/test.png
  src/assets/serviceList/index.ts
  src/components/Common/Nav/NavLink.tsx
  src/components/Common/Nav/ServeNav.tsx
  src/components/ListCard/index.tsx
  src/components/Nav/index.tsx
  src/pages/List/It.tsx
  src/pages/List/Media.tsx
  src/pages/List/Sw.tsx
  src/pages/List/index.tsx
  src/router/index.tsx
Labels: feat

#16 Style/main 수정 후 풀리퀘스트
  package-lock.json
  package.json
  src/assets/images/main_intro.json
  src/components/ListCard/index.tsx
  src/components/MainCard/mainintro.tsx
  src/pages/Main/index.tsx
  src/styles/GlobalStyle.tsx
Labels: style

#18 [#15] apply Detail page
  package-lock.json
  package.json
  src/assets/serviceList/index.ts
  src/components/Common/Nav/ServeNav.tsx
  src/components/Detail/GoLink.tsx
  src/components/Detail/Inform.tsx
  src/components/ListCard/index.tsx
  src/pages/Detail/index.tsx
  src/pages/List/It.tsx
  src/pages/List/Media.tsx
  src/pages/List/Sw.tsx
Labels: feat

#21 [#19] modify page style by resizing nav
  src/components/Common/Nav/NavLink.tsx
  src/components/Nav/index.tsx
  src/pages/Detail/index.tsx
  src/pages/List/It.tsx
  src/pages/List/Media.tsx
  src/pages/List/Sw.tsx
Labels: style

#23 modify main page error
  src/components/MainCard/mainintro.tsx
Labels: bug

#24 Feat/not found
  src/assets/lottieJSON/main_intro.json
  src/assets/lottieJSON/notfound.json
  src/components/MainCard/mainintro.tsx
  src/components/Nav/index.tsx
  src/components/NotFound/notf.tsx
  src/pages/Main/index.tsx
  src/pages/NotFound/index.tsx
Labels: feat

#31 [#22] apply signin page style
  LICENSE
  src/assets/lottieJSON/hello.json
  src/components/Common/LottieWrapper.tsx
  src/components/Nav/index.tsx
  src/pages/Signin/HelloLottie.tsx
  src/pages/Signin/index.tsx
  src/router/index.tsx
Labels: feat

#34 Feat/meet
  package-lock.json
  package.json
  src/assets/images/anonymous.png
  src/assets/images/frame.png
  src/assets/images/notfound.json
  src/assets/images/phone-call.png
  src/assets/images/share.png
  src/assets/images/video.png
  src/assets/images/voice.png
  src/components/Common/Button/CopyButton.tsx
  src/components/MeetCard/meet.tsx
  src/components/NotFound/index.tsx
  src/pages/Meet/index.tsx
  src/router/index.tsx
Labels: feat

#35 [#30] apply mainPage markup, style
  package-lock.json
  package.json
  src/assets/images/computer.png
  src/assets/images/phone.png
  src/assets/lottieJSON/circle.json
  src/assets/lottieJSON/main_intro.json
  src/assets/lottieJSON/student.json
  src/components/Common/Footer.tsx
  src/components/Main/Bottom.tsx
  src/components/Main/Explain.tsx
  src/components/Main/Header.tsx
  src/components/MainCard/mainintro.tsx
  src/constants/motion/index.ts
  src/pages/Main/IntroLottie.tsx
  src/pages/Main/StudentLottie.tsx
  src/pages/Main/index.tsx
  tsconfig.json
Labels: feat

#38 [#36] modify logo name
  public/index.html
  src/components/Nav/index.tsx
  src/pages/Signin/index.tsx
Labels: style

#39 Feat/write
  src/components/MeetCard/meet.tsx
  src/components/WriteCard/index.tsx
  src/pages/Meet/index.tsx
Labels: feat

#45 [#44] apply media query Nav
  src/components/Common/Footer.tsx
  src/components/ListCard/index.tsx
  src/components/Main/Bottom.tsx
  src/components/Main/Chapter.tsx
  src/components/Main/Explain.tsx
  src/components/Main/Header.tsx
  src/components/Main/IosPart.tsx
  src/components/Nav/index.tsx
  src/pages/Detail/index.tsx
  src/pages/List/It.tsx
  src/pages/List/Media.tsx
  src/pages/List/Sw.tsx
  src/pages/Main/index.tsx
  src/pages/Signin/index.tsx
  src/styles/theme.ts
Labels: style

#46 [#40] apply google analytics
  .gitignore
  package-lock.json
  package.json
  src/hooks/useGa.ts
  src/router/index.tsx
Labels: env

#53 [#52] apply Media Query
  src/components/Common/Footer.tsx
  src/components/Main/Bottom.tsx
  src/components/Main/Chapter.tsx
  src/components/Main/Header.tsx
  src/components/Main/IosPart.tsx
  src/components/Nav/index.tsx
  src/pages/Main/index.tsx
  src/pages/Signin/index.tsx
Labels: feat
